### PR TITLE
feat: add polls support

### PR DESCRIPTION
**Pull request by Azn9**
https://github.com/discord/discord-api-docs/pull/6746

### CODE REVIEW

**Comment by Azn9** [comment]
On hold until some comments on the api docs pr are resolved:
- https://github.com/discord/discord-api-docs/pull/6746/files#r1536461865
- https://github.com/discord/discord-api-docs/pull/6746/files#r1536188080
- https://github.com/discord/discord-api-docs/pull/6746/files#r1534836790

**Review by Doc94 — CHANGES_REQUESTED** [review]

**Comment by Azn9** [comment]
I also need to add the new permission

**Comment by Azn9** [comment]
Hello @Doc94 I updated everything based on the latest documentation!

**Review by Doc94 — APPROVED** [review]
LGTM.
but i wanna wait for the PR in D4J before merge this.

**Comment by Azn9** [comment]
> LGTM. but i wanna wait for the PR in D4J before merge this.

I'm working on it!

**Pull request merged**
