### PR TITLE
Add support for context menu commands

### PR DESCRIPTION
**Pull request by NovaFox161**
This adds support for the new context menu commands (USER and MESSAGE types)

### Added
* `type` field of `Possible<Integer>` to `ApplicationCommandData`
* `type` field of `Possible<Integer>` to `ApplicationCommandRequest`

### Changed
* `description` field changed to `Possible<String>` in `ApplicationCommandRequest`
  * Justification: Field not allowed when creating USER or MESSAGE type commands.
  * This field returns an empty string when fetching commands so type-change is not needed in its data counterpart.
*  `message` field changed to `Possible<MessageData>` in `InteractionData`
    * Justification: Discord no longer returns partial data for interactions on ephemeral messages.
* Documentation on `description` and `name` fields in changed classes
  * Justification: Discord only applies the regex to CHAT_INPUT type commands, MESSAGE and USER types are only bound by the character count limit.
  
### Justification & Related Issues/PRs
* https://github.com/discord/discord-api-docs/pull/3614
* https://github.com/Discord4J/Discord4J/issues/983
* https://github.com/Discord4J/Discord4J/pull/996

### CODE REVIEW

**Comment by darichey** [comment]
> Justification: Field not allowed when creating USER or MESSAGE type commands.

I'm not seeing this in the docs (and `description` isn't marked as optional there either)

**Comment by Laarryy** [comment]
> > Justification: Field not allowed when creating USER or MESSAGE type commands.
> 
> I'm not seeing this in the docs (and `description` isn't marked as optional there either)

Found it - https://discord.com/developers/docs/interactions/application-commands#user-commands

Here's what my screen shows in case it's different on your end https://i.imgur.com/7cQelsz.png

**Comment by NovaFox161** [comment]
It's not marked clearly in the object, but that note is present on the sections about creating user/message commands. I'm not sure if discord shoots back an error if the field is included, or just ignores it completely since several things relating to application commands aren't directly documented and just have little notes peppered around the docs about behavior (for example, the command names only having the regex applied for chat input commands)

**Review by WeeskyBDW — APPROVED** [review]
Loog good to me

**Review by quanticc — APPROVED** [review]

**Pull request merged**
