### PR TITLE
feat(): replaced the List<String> for GuildFields features by an Enum…

### PR DESCRIPTION
**Pull request by gmisiurny**
**Description** : https://github.com/Discord4J/Discord4J/issues/1196#issue-2198638402

**Justification** : Discord4J `GuildFields` interface rely on this repository.

### CODE REVIEW

**Comment by Doc94** [comment]
Why PermissionSet?

**Comment by gmisiurny** [comment]
I can change the name of the enum if you want. `PermissionSet` is what @Azn9 suggested.
Maybe GuildFeature or GuildPermission is more suitable ?

**Review by Azn9 — CHANGES_REQUESTED** [review]
Thank you for your contribution!

However, there are some changes required on this PR.
In fact, this PR is not needed. The conversion from a List<String> to a EnumSet should be done only on the Discord4J part. The discord-json project aims to represent discord entities as immutables objects in their most basic form.
You can take example on the message data flags field for instance

https://github.com/Discord4J/discord-json/blob/cc21386382ebf53feba982d9efff688d7c0a8102/src/main/java/discord4j/discordjson/json/MessageData.java#L79

https://github.com/Discord4J/Discord4J/blob/026c1b8aa424d18679331102043ceab3d8e6fc74/core/src/main/java/discord4j/core/object/entity/Message.java#L427C1-L431C6

For the "PermissionSet", I just said "something like", to replace a EnumSet. Have a look at the file https://github.com/Discord4J/Discord4J/blob/master/rest/src/main/java/discord4j/rest/util/PermissionSet.java

**Comment by Doc94** [comment]
Closed in favor of https://github.com/Discord4J/Discord4J/pull/1207
Like Azn9 this project represent the data in the most direct way.

**Pull request closed without merging**
