### PR TITLE
Adds WebhookMessageEditRequest#attachments

### PR DESCRIPTION
**Pull request by Shadorc**
**Justification:** https://github.com/discord/discord-api-docs/commit/5afbad75892a907726ab47eea4d9bcbeabcdaa18

### CODE REVIEW

**Comment by quanticc** [comment]
We need further tests to validate if this is the right way to work with the feature. For message creation, payload_json and file fields are passed as form fields in the multipart request.

**Comment by darichey** [comment]
Would the same confirmation be needed for #78?

**Comment by quanticc** [comment]
After looking at docs, this PR should only cover the `attachments` field like #78 - "attached files to keep" when patching a (webhook) message.

Tests would help to know if you can add more attachments when editing (using multipart payload_json + file) or if it's just for keeping 0..N original attachments (json request body)

**Comment by Shadorc** [comment]
I have updated my PR to remove the `payload_json` field.

**Pull request merged**
